// Auth types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED'


// Cards types
export const FETCH_ALL_CARDS_SUCCESS = 'FETCH_ALL_CARDS_SUCCESS'
export const FETCH_ALL_CARDS_FAILURE = 'FETCH_ALL_CARDS_FAILURE'

export const SEARCH_CARDS_SUCCESS = 'SEARCH_CARDS_SUCCESS'
export const SEARCH_CARDS_FAILURE = 'SEARCH_CARDS_FAILURE'

export const CLEAR_CARDS = 'CLEAR_CARDS'

// General purpose types
export const LOADING_ENABLED = 'LOADING_ENABLED'
export const LOADING_DISABLED = 'LOADING_DISABLED'
